# .scrutinizer.yml
checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ['src/*']
    
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
       php: 7.2
       postgresql: true
    tests:
            override:
                -
                    command: './vendor/bin/phpunit --coverage-clover=clover.xml -c ./phpunit.scrutinizer.xml'
                    coverage:
                        file: 'clover.xml'
                        format: 'clover'

    project_setup:
            before:
                - PGPASSWORD=scrutinizer psql -U scrutinizer -p 5435 -a -f vendor/linna/db-dumps/src/linna_db_pgsql_test_scrutinizer.sql