# .scrutinizer.yml
checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ['src/*']
    
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
       php: 7.1
       postgresql: true
    tests:
            override:
                -
                    command: './vendor/bin/phpunit --coverage-clover=clover.xml'
                    coverage:
                        file: 'clover.xml'
                        format: 'clover'

    project_setup:
            before:
                - sed -i 's/pgsql:dbname=linna_db;host=localhost/pgsql:dbname=scrutinizer;host=localhost;port=5435/g' phpunit.xml
                - sed -i 's/name="pdo_pgsql_user" value="postgres"/name="pdo_pgsql_user" value="scrutinizer"/g' phpunit.xml
                - sed -i 's/name="pdo_pgsql_password" value=""/name="pdo_pgsql_password" value="scrutinizer"/g' phpunit.xml
                - PGPASSWORD=scrutinizer psql -U scrutinizer -p 5435 -a -f vendor/linna/db-dumps/src/linna_db_pgsql_test_scrutinizer.sql